# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
loom.platform = fabric

# Mod properties
mod_version = 1.0.0
maven_group = org.lantern
archives_name = Lantern

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
fabric_loader_version = 0.16.10
fabric_api_version = 0.116.8+1.21.1

# Geckolib
geckolib_version = 4.7.1