name: Lantern
main: org.lantern.LanternPlugin
depend:
  - AyCore
softdepend:
  - PlaceholderAPI
  - MythicMobs
version: ${version}
api-version: 1.20
commands:
  lantern:
    description: Lantern 管理命令。
    usage: /lantern [reload|open <界面ID> [玩家]|give <方块ID> [玩家] [数量]|anim play <动画名> [过渡tick] [loop|once]|anim stop <动画名> [过渡tick]|cam info [玩家]|cam toggle [玩家]|cam set <offset-x|offset-y|distance> <值> [玩家]|cam lock <x> <y> <z> [平滑秒] [持续秒] [sync] [玩家]|cam lockentity [平滑秒] [持续秒] [sync] [玩家]|cam unlock [玩家]|cam shake [幅度] [频率] [时长秒] [玩家]|cam fov [度数] [过渡秒] [玩家]|cam offset <pitch> <yaw> [roll] [过渡秒] [玩家]|cam path <路径ID> [玩家] [速度]|cam watch <x> <y> <z> <看向x> <看向y> <看向z> [持续秒] [平滑秒] [玩家]|cam clear [玩家]|campath start <路径ID>|campath add [t] [linear|smooth|hold] [fov]|campath undo|clear|list|preview|play [速度]|save|stop|costume equip <玩家> <槽位> <装扮ID>|costume unequip <玩家> [槽位]|wardrobe [玩家]]