modLoader="javafml"
loaderVersion="[47,)"
license="All-Rights-Reserved"
clientSideOnly=true

[[mods]]
modId="lantern"
version="${version}"
displayName="Lantern"
description="Lantern client mod"

[[dependencies.lantern]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.lantern]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="CLIENT"
