license="All-Rights-Reserved"

[[mods]]
modId="lantern"
version="${version}"
displayName="Lantern"
authors="Lantern"
description='''Lantern client mod'''

[[mixins]]
config="lantern-neoforge-12110.mixins.json"

[[dependencies.lantern]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version}]"
ordering="NONE"
side="CLIENT"

[[dependencies.lantern]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="CLIENT"

[[dependencies.lantern]]
modId="geckolib"
type="required"
versionRange="[${geckolib_version}]"
ordering="AFTER"
side="CLIENT"
